[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.17.0"
raylib = "5.5.1"
rayon = "1.10.0"
bvh = "0.4.0"
nalgebra = "0.26.2"

[profile.dev]
opt-level = 3
debug = false
